### PR TITLE
Add autoconfiguration of partials loader.

### LINKED ISSUE #10: Add wrap_loaders() helper.
Currently one has to override the template loaders manually in order to add the partials loader. 
That's rubbish. 

Much better would be a `wrap_loaders()` helper that could do this for you. 

* Should be called from an `AppConfig.ready()`
* The `template_partials` app should provide a default `AppConfig` that does this. 
    *  People would just then add `template_partials` to `INSTALLED_APPS` and they'd be done. 
* For completeness, an optional `AppConfig` that doesn't do this can be added, so that folks can opt-out.

(I'm happy to elaborate if needed.)

### PR DESCRIPTION
**Pull request by vsajip**
Should fix #10. I didn't create a separate `wrap_loaders()` function as I wasn't sure where it would be called / where it should go if called from outside this package. Would appreciate your comments!

### CODE REVIEW

**Comment by vsajip** [comment]
Hmmm. GitHub Actions failing, but tests run fine locally ...
```
$ just test
django-admin test --settings=tests.settings --pythonpath=. 
Found 5 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
Destroying test database for alias 'default'...

$ just coverage
coverage erase
coverage run -m django test --settings=tests.settings --pythonpath=.
Found 5 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.....
----------------------------------------------------------------------
Ran 5 tests in 0.012s

OK
Destroying test database for alias 'default'...
coverage report
Name                                             Stmts   Miss  Cover
--------------------------------------------------------------------
src/template_partials/__init__.py                    1      0   100%
src/template_partials/apps.py                       19      0   100%
src/template_partials/loader.py                     30      7    77%
src/template_partials/templatetags/__init__.py       0      0   100%
src/template_partials/templatetags/partials.py      53      4    92%
tests/__init__.py                                    0      0   100%
tests/settings.py                                    5      0   100%
tests/templates/debug.html                           8      0   100%
tests/templates/example.html                        12      0   100%
tests/tests.py                                      35      0   100%
--------------------------------------------------------------------
TOTAL                                              163     11    93%
```

**Review by carltongibson — COMMENTED** [review]
This looks good @vsajip thanks. Let me have a play next week. 🎁

**Comment by vsajip** [comment]
Did you get a chance to take a look, @carltongibson?

**Comment by carltongibson** [comment]
Hey @vsajip, no not yet. I have a few personal issues going on right now that have kept me away. I will get to it though! Thanks for the input.

**Review by carltongibson — COMMENTED** [review]
Hi @vsajip — thanks for this. 

Are you up for making a few adjustments? 

1. I think pull the logic out into a `wrap_loaders` function, and let it take a backend alias, so that folks use it themselves, no matter their setup. (Then call that with the default backend from the default AppConfig.)
2. Update the instructions in the README to say _Just add to INSTALLED_APPS_, unless... Then mention the app loader integration, and that you can use the `BaseAppConfig` — I'd call that `SimpleAppConfig` — and that the `wrap_loaders` function is available if you need to use it, for example if you have multiple backends. 
3. I would leave and adjust the existing example, so people have that if they need it. 

I.e. Imagine you turned up to the project… What would the README need to say so that you could get set up without obstacle? 

Let me know if that makes sense. Thanks!

**Comment by carltongibson** [comment]
Great. Thanks! 🎁

**Comment by carltongibson** [comment]
I mean the `NAME` key, which you'd use in particular if configuring multiple Django backends.

**Comment by vsajip** [comment]
> I mean the NAME key

Oh, I see. That was under my radar as I've never actually used it - never had to configure several instances of the same backend with different options.

Also,

> I would leave and adjust the existing example, so people have that if they need it.

Do you mean the usage example? I'm assuming the example of configuration of the loaders isn't needed, as `wrap_loaders` does it and it's not needed in common usage.

**Comment by vsajip** [comment]
So just leave as is, but move to where "wrap_loaders" is mentioned?

**Comment by carltongibson** [comment]
Yeah...

Option 1 is just add to installed apps. 

Option 2 is use the simple AppConfig but then configure loaders yourself (either with wrap loaders or by hand)

**Comment by vsajip** [comment]
I've pushed [changes ](https://github.com/vsajip/django-template-partials/commits/appconfig) addressing your comments, but for some reason GitHub hasn't picked them up.

**Comment by vsajip** [comment]
I've logged [an issue](https://support.github.com/ticket/personal/0/2274696) with GitHub, let's see what happens.

**Comment by vsajip** [comment]
The GH issue appears to have resolved itself. My last commit is now showing, so you should be able to review my changes.

**Comment by vsajip** [comment]
Oh hey, no worries! I'm using this library, liking it, and I like to give back. Take your time :smile:

**Comment by carltongibson** [comment]
@vsajip Thanks for your patience here. Just so you know, I'll looking at this now, and am hoping to do a release for a new version in the next week or so. 🎁

**Review by carltongibson — APPROVED** [review]
Great. Thanks for this @vsajip. 🎁

**Pull request merged**
