### PR TITLE
:pencil: pypi changelog fix

### PR DESCRIPTION
**Pull request by jefftriplett**
This is a fix for the README's rendering on pypi. Feel free to ignore it :) 

https://pypi.org/project/django-template-partials/

### CODE REVIEW

**Comment by jefftriplett** [comment]
A good alternative might be to add the changelog to the sidebar as an optional link if you'd prefer.

**Review by carltongibson — APPROVED** [review]
Good call. Thanks @jefftriplett

**Comment by carltongibson** [comment]
> A good alternative might be to add the changelog to the sidebar as an optional link if you'd prefer.

We could do that as well if you like.

**Comment by jefftriplett** [comment]
Danke! 🎉

**Pull request merged**
